/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ZodiacSignService } from "../zodiacSign.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ZodiacSignCreateInput } from "./ZodiacSignCreateInput";
import { ZodiacSign } from "./ZodiacSign";
import { ZodiacSignFindManyArgs } from "./ZodiacSignFindManyArgs";
import { ZodiacSignWhereUniqueInput } from "./ZodiacSignWhereUniqueInput";
import { ZodiacSignUpdateInput } from "./ZodiacSignUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ZodiacSignControllerBase {
  constructor(
    protected readonly service: ZodiacSignService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ZodiacSign })
  @nestAccessControl.UseRoles({
    resource: "ZodiacSign",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createZodiacSign(
    @common.Body() data: ZodiacSignCreateInput
  ): Promise<ZodiacSign> {
    return await this.service.createZodiacSign({
      data: data,
      select: {
        createdAt: true,
        dateRange: true,
        element: true,
        id: true,
        name: true,
        quality: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ZodiacSign] })
  @ApiNestedQuery(ZodiacSignFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ZodiacSign",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async zodiacSigns(@common.Req() request: Request): Promise<ZodiacSign[]> {
    const args = plainToClass(ZodiacSignFindManyArgs, request.query);
    return this.service.zodiacSigns({
      ...args,
      select: {
        createdAt: true,
        dateRange: true,
        element: true,
        id: true,
        name: true,
        quality: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ZodiacSign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ZodiacSign",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async zodiacSign(
    @common.Param() params: ZodiacSignWhereUniqueInput
  ): Promise<ZodiacSign | null> {
    const result = await this.service.zodiacSign({
      where: params,
      select: {
        createdAt: true,
        dateRange: true,
        element: true,
        id: true,
        name: true,
        quality: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ZodiacSign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ZodiacSign",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateZodiacSign(
    @common.Param() params: ZodiacSignWhereUniqueInput,
    @common.Body() data: ZodiacSignUpdateInput
  ): Promise<ZodiacSign | null> {
    try {
      return await this.service.updateZodiacSign({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dateRange: true,
          element: true,
          id: true,
          name: true,
          quality: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ZodiacSign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ZodiacSign",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteZodiacSign(
    @common.Param() params: ZodiacSignWhereUniqueInput
  ): Promise<ZodiacSign | null> {
    try {
      return await this.service.deleteZodiacSign({
        where: params,
        select: {
          createdAt: true,
          dateRange: true,
          element: true,
          id: true,
          name: true,
          quality: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
