/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CompatibilityService } from "../compatibility.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CompatibilityCreateInput } from "./CompatibilityCreateInput";
import { Compatibility } from "./Compatibility";
import { CompatibilityFindManyArgs } from "./CompatibilityFindManyArgs";
import { CompatibilityWhereUniqueInput } from "./CompatibilityWhereUniqueInput";
import { CompatibilityUpdateInput } from "./CompatibilityUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CompatibilityControllerBase {
  constructor(
    protected readonly service: CompatibilityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Compatibility })
  @nestAccessControl.UseRoles({
    resource: "Compatibility",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCompatibility(
    @common.Body() data: CompatibilityCreateInput
  ): Promise<Compatibility> {
    return await this.service.createCompatibility({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        sign1: true,
        sign2: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Compatibility] })
  @ApiNestedQuery(CompatibilityFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Compatibility",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async compatibilities(
    @common.Req() request: Request
  ): Promise<Compatibility[]> {
    const args = plainToClass(CompatibilityFindManyArgs, request.query);
    return this.service.compatibilities({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        sign1: true,
        sign2: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Compatibility })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Compatibility",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async compatibility(
    @common.Param() params: CompatibilityWhereUniqueInput
  ): Promise<Compatibility | null> {
    const result = await this.service.compatibility({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        sign1: true,
        sign2: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Compatibility })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Compatibility",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCompatibility(
    @common.Param() params: CompatibilityWhereUniqueInput,
    @common.Body() data: CompatibilityUpdateInput
  ): Promise<Compatibility | null> {
    try {
      return await this.service.updateCompatibility({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          sign1: true,
          sign2: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Compatibility })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Compatibility",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCompatibility(
    @common.Param() params: CompatibilityWhereUniqueInput
  ): Promise<Compatibility | null> {
    try {
      return await this.service.deleteCompatibility({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          sign1: true,
          sign2: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
